imports:
    - { resource: src/Framework/services.yaml }

services:

  _defaults:
    public: false
    autowire: true

  OxidEsales\GraphQL\Base\Infrastructure\ModuleSetup:
    class: OxidEsales\GraphQL\Base\Infrastructure\ModuleSetup
    public: true

  OxidEsales\GraphQL\Base\Framework\TimerHandler:
    class: OxidEsales\GraphQL\Base\Framework\TimerHandler
    public: true

  OxidEsales\GraphQL\Base\Service\ModuleConfiguration:
    class: OxidEsales\GraphQL\Base\Service\ModuleConfiguration
    public: true

  OxidEsales\GraphQL\Base\Service\JwtConfigurationBuilder:
    class: OxidEsales\GraphQL\Base\Service\JwtConfigurationBuilder
    public: true

  Lcobucci\JWT\UnencryptedToken:
    factory: ['@OxidEsales\GraphQL\Base\Framework\RequestReader', 'getAuthToken']

  OxidEsales\GraphQL\Base\Service\Authentication:
    class: OxidEsales\GraphQL\Base\Service\Authentication
    public: true

  OxidEsales\GraphQL\Base\Service\Token:
    class: OxidEsales\GraphQL\Base\Service\Token
    public: true

  OxidEsales\GraphQL\Base\Service\TokenValidator:
      class: OxidEsales\GraphQL\Base\Service\TokenValidator

  OxidEsales\GraphQL\Base\Service\TokenAdministration:
      class: OxidEsales\GraphQL\Base\Service\TokenAdministration

  OxidEsales\GraphQL\Base\Infrastructure\Legacy:
    class: OxidEsales\GraphQL\Base\Infrastructure\Legacy

  OxidEsales\GraphQL\Base\Infrastructure\Token:
      class: OxidEsales\GraphQL\Base\Infrastructure\Token

  OxidEsales\GraphQL\Base\Infrastructure\Repository:
      class: OxidEsales\GraphQL\Base\Infrastructure\Repository

  OxidEsales\GraphQL\Base\Service\Authorization:
    class: OxidEsales\GraphQL\Base\Service\Authorization
    arguments:
        $permissionProviders: !tagged graphql_permission_provider

  OxidEsales\GraphQL\Base\Controller\:
    resource: 'src/Controller/'
    public: true

  OxidEsales\GraphQL\Base\Service\NamespaceMapper:
    class: OxidEsales\GraphQL\Base\Service\NamespaceMapper
    tags: ['graphql_namespace_mapper']

  OxidEsales\GraphQL\Base\Framework\SchemaFactory:
    class: OxidEsales\GraphQL\Base\Framework\SchemaFactory
    arguments:
      $namespaceMappers: !tagged graphql_namespace_mapper
      $container: '@service_container'
      $cache: '@oxidesales.graphqlbase.cache'

  OxidEsales\GraphQL\Base\Event\Subscriber\ModuleChangeSubscriber:
    class: OxidEsales\GraphQL\Base\Event\Subscriber\ModuleChangeSubscriber
    public: true
    arguments:
      $cache: '@oxidesales.graphqlbase.cache'
    tags:
      - {name: kernel.event_subscriber}

  OxidEsales\GraphQL\Base\Event\Subscriber\UserDeleteSubscriber:
    class: OxidEsales\GraphQL\Base\Event\Subscriber\UserDeleteSubscriber
    tags: [ 'kernel.event_subscriber' ]

  oxidesales.graphqlbase.cacheadapter:
    class: Symfony\Component\Cache\Adapter\NullAdapter

  oxidesales.graphqlbase.cache:
    class: Symfony\Component\Cache\Psr16Cache
    arguments:
      $pool: '@oxidesales.graphqlbase.cacheadapter'

  OxidEsales\GraphQL\Base\Service\PermissionProvider:
      class: OxidEsales\GraphQL\Base\Service\PermissionProvider
      tags: [ 'graphql_permission_provider' ]
